name: Daily Mirror Backup

on:
  schedule:
    - cron: '0 1 * * *'  # every day at 1 AM UTC
  workflow_dispatch:      # optional: allows manual run from GitHub UI

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror source repo
        run: |
          git config --global user.name "Backup Bot"
          git config --global user.email "backup@bot.com"
          
          # Clone the curiouspods/backend repo with --mirror
          git clone --mirror https://github.com/curiouspods/backend.git
          cd backend.git

          # Set the push URL to the backup repo (Vtexhealthtech/mirror_backup)
          git remote set-url --push origin https://Vtexhealthtech:${{ secrets.GH_PAT }}@github.com/Vtexhealthtech/mirror_backup.git

          # Push all branches, tags, and refs to backup
          git push --mirror
